### ISSUE TITLE
Gen:Variant.Razy.594931 virus threat detected in the executable

### ISSUE THREAD

**Issue by cristi-neagu** [Touille/ED-Warthog-Target-Script#40]
Hello,

Looks like Bitdefender is very adamant that there is a virus threat in the executable file. Can anyone confirm this?

Thank you.

**Comment by ClickerNZ** [comment]
I am not the author, however,I am certain that no virus exists.
The source code is included so you check it out and recompile the exe yourself if that will ease your mind.
